#!/usr/bin/env bash
root_dir="/opt/lantern"
service_name="lantern-server-manager"
service_unit="lantern-server-manager.service"
sysvinit_script="lantern-server-manager.sysvinit"
sysvinit_dir="/etc/init.d/"

error(){
    echo -e "\e[91m$(date "+%Y-%m-%d %H:%M:%S.%3N")\t[ERRO]\t$1\e[0m"
}
warn(){
    echo -e "\e[93m$(date "+%Y-%m-%d %H:%M:%S.%3N")\t[WARN]\t$1\e[0m"
}
info(){
    echo -e "\e[96m$(date "+%Y-%m-%d %H:%M:%S.%3N")\t[INFO]\t$1\e[0m"
}
succ(){
    echo -e "\e[92m$(date "+%Y-%m-%d %H:%M:%S.%3N")\t[SUCC]\t$1\e[0m"
}

expect(){
    $1
    rtc=$?
    if [ $rtc -ne 0 ]; then
        if [ -n "$2" ]; then
            $2
        fi
	    error "when exec $1, an unexpected error occurred, code: $rtc"
	    exit $rtc
	fi
}

disable_service() {
  	info "disable service"
  	if command -v systemctl >/dev/null;then
  	    expect "systemctl disable ${service_unit}"
    elif command -v update-rc.d >/dev/null || command -v chkconfig >/dev/null;then
        expect "update-rc.d -f ${service_name} remove"
        expect "chkconfig --del ${service_name}"
    else
        error "systemd/sysvinit not detected"
        exit 1
    fi
    succ "service disabled successfully"
}


clean_dirs() {
    rm -rf ${root_dir}
}

disable_service
clean_dirs
