# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: lantern-server-manager
metadata:
  maintainers:
    - "Lantern Team <dev@getlantern.org>"
  description: Lantern Server Manager
  homepage: "https://github.com/getlantern/lantern-server-manager"
  license: "GPL"

builds:
  - main: ./cmd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags=-static

    binary: lantern-server-manager

archives:
  - formats: ["tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  replace_existing_artifacts: true

nfpms:
  - package_name: "lantern-server-manager"
    formats:
      - deb
      - rpm
    section: "default"
    maintainer: "Lantern Team <dev@getlantern.org>"
    description: |
      Lantern Server Manager
    vendor: "Brave New Software"
    homepage: "https://github.com/getlantern/lantern-headless-client"
    license: "GPL"
    contents:
      - src: ./cloud/lantern-server-manager.service
        dst: /opt/lantern/lantern-server-manager.service
        file_info:
          mode: 0600
          owner: root
          group: root
    scripts:
      postinstall: ./cloud/postinstall
      preremove: ./cloud/preremove
      preinstall: ./cloud/preinstall

furies:
  - account: getlantern
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "getlantern/lantern-server-manager:latest"
      - "getlantern/lantern-server-manager:{{ .Tag }}"

dockerhub:
  - images:
      - getlantern/lantern-server-manager
    username: getlantern
    secret_name: DOCKER_PASSWORD
    full_description:
      from_file:
        path: ./README.md
