---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Add repository for lantern projects
      yum_repository:
        name: lantern-projects
        description: lantern-projects YUM repo
        baseurl: https://getlantern.fury.site/yum/
        gpgcheck: no
      when: ansible_os_family == "RedHat"
        
    - name: Add deb repository for lantern projects
      apt_repository:
        state: present
        repo: deb [trusted=yes] https://apt.fury.io/getlantern/ /
      when: ansible_os_family == "Debian"

    - name: install packages
      package:
        name:
          - lantern-server-manager
          - sing-box-extensions
          - fail2ban
          - firewalld
        state: present

    - name: enable fail2ban
      systemd:
          name: fail2ban
          enabled: true
          state: started

    - name: setup firewalld for port 22 only
      ansible.posix.firewalld:
          service: ssh
          permanent: true
          state: enabled
          immediate: no

    - name: ensure values are set correctly in sysctl
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
        reload: yes
      loop:
        - name: 'fs.file-max'
          value: '67108864'
        - name: 'net.core.default_qdisc'
          value: 'fq'
        - name: 'net.core.optmem_max'
          value: '262144'
        - name: 'net.core.rmem_max'
          value: '33554432'
        - name: 'net.core.wmem_max'
          value: '33554432'
        - name: 'net.ipv4.tcp_congestion_control'
          value: 'bbr'
        - name: 'net.ipv4.tcp_max_syn_backlog'
          value: '10240'
        - name: 'net.ipv4.tcp_fin_timeout'
          value: '25'
        - name: 'net.core.netdev_max_backlog'
          value: '32768'

    - name: Create journal directory
      file:
        path: '/var/log/journal'
        state: 'directory'
    - name: Set journal directory permissions
      command: 'systemd-tmpfiles --create --prefix /var/log/journal'
    - name: Restart journald
      service:
        name: 'systemd-journald'
        state: 'restarted'
